// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: channels.sql

package db

import (
	"context"
	"database/sql"
)

const createChannel = `-- name: CreateChannel :execresult
INSERT INTO channel (
  name, created_by
) VALUES (
   ?, ?
)
`

type CreateChannelParams struct {
	Name      sql.NullString `json:"name"`
	CreatedBy sql.NullInt32  `json:"created_by"`
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createChannel, arg.Name, arg.CreatedBy)
}

const joinChannel = `-- name: JoinChannel :execresult
INSERT INTO channel_user (
  user_id, channel_id
) VALUES (
   ?, ?
)
`

type JoinChannelParams struct {
	UserID    sql.NullInt32 `json:"user_id"`
	ChannelID sql.NullInt32 `json:"channel_id"`
}

func (q *Queries) JoinChannel(ctx context.Context, arg JoinChannelParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, joinChannel, arg.UserID, arg.ChannelID)
}
