// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: message.sql

package db

import (
	"context"
	"database/sql"
)

const sendMessage = `-- name: SendMessage :execresult
INSERT INTO messages(
  user_id, channel_id, message
) VALUES (
   ?, ?, ?
)
`

type SendMessageParams struct {
	UserID    sql.NullInt32  `json:"user_id"`
	ChannelID sql.NullInt32  `json:"channel_id"`
	Message   sql.NullString `json:"message"`
}

func (q *Queries) SendMessage(ctx context.Context, arg SendMessageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, sendMessage, arg.UserID, arg.ChannelID, arg.Message)
}
