// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
)

type Users struct {
	ID        int32          `json:"id"`
	Fullname  string `json:"fullname"`
	Email     string `json:"email"`
	Username  string `json:"username"`
	Password  string `json:"password"`
	Profile   string `json:"profile"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
