// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
)

type Channel struct {
	ID        int32          `json:"id"`
	Name      sql.NullString `json:"name"`
	CreatedBy sql.NullInt32  `json:"created_by"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type ChannelUser struct {
	ID        int32         `json:"id"`
	UserID    sql.NullInt32 `json:"user_id"`
	ChannelID sql.NullInt32 `json:"channel_id"`
}

type Messages struct {
	ID        int32          `json:"id"`
	UserID    sql.NullInt32  `json:"user_id"`
	ChannelID sql.NullInt32  `json:"channel_id"`
	Messages  sql.NullString `json:"messages"`
	CreatedAt sql.NullTime   `json:"created_at"`
}

type User struct {
	ID        int32          `json:"id"`
	Email     sql.NullString `json:"email"`
	Username  sql.NullString `json:"username"`
	Password  sql.NullString `json:"password"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
