import { Box, TextField, Button } from "@mui/material";
import Head from "next/head";
import React from "react";
import { io } from "socket.io-client";

export default function Home() {
   const [message, setMessage] = React.useState("");
   const socket = io("http://localhost:8000/ws", {
      withCredentials: true,
      extraHeaders: {
         "my-custom-header": "abcd",
      },
   });

   const sendMessage = async (params: any) => {
      try {
         // send a message to the server
         socket.emit(message, 5, "6", { 7: Uint8Array.from([8]) });
      } catch (error: any) {
         console.log(error);
      }
   };

   return (
      <>
         <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
            <meta
               name="viewport"
               content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <form method="POST">
            <TextField
               onChange={(e: any) => setMessage(e)}
               id="outlined-basic"
               label="Outlined"
               variant="outlined"
            />
            <Button onClick={sendMessage} variant="text">
               Send
            </Button>
         </form>
      </>
   );
}
